Chapter 18 orm 2
LaunchCodeEducation/csharp-web-dev-curriculum pull request #31
Opened 2023-03-13 20:10 UTC by jwoolbright23

2023-03-21 19:49 UTC, codinglikeagirl42 commented on content/relationships-or-mapping/reading/types-of-relationships/_index.md
> +Just as database tables [can relate]() to each other, so can classes and objects. In fact, ORM translates relationships between objects into relationships between database rows.
```suggestion
Just as database tables [can relate](https://education.launchcode.org/SQL/chapters/mysql-part-2/relationships.html#relating-data) to each other, so can classes and objects. In fact, ORM translates relationships between objects into relationships between database rows.
```

2023-03-22 15:41 UTC, codinglikeagirl42 commented on content/relationships-or-mapping/exercises/_index.md
> +lastMod: 12/15/22 # UPDATE ANY TIME CHANGES ARE MADE
```suggestion
lastMod: # UPDATE ANY TIME CHANGES ARE MADE
```

2023-03-22 15:57 UTC, codinglikeagirl42 commented on content/relationships-or-mapping/exercises/_index.md
> +date: 2022-12-15T09:16:07-06:00
These dates seem incorrect as the chapter was started on 3/16/2023

2023-03-22 15:57 UTC, codinglikeagirl42 commented on content/relationships-or-mapping/_index.md
> +lastMod: 12/15/22 # UPDATE ANY TIME CHANGES ARE MADE
```suggestion
lastMod: # UPDATE ANY TIME CHANGES ARE MADE
```

2023-03-22 15:58 UTC, codinglikeagirl42 commented on content/relationships-or-mapping/next-steps.md
> +date: 2022-12-15T09:16:07-06:00
These dates seem incorrect as the chapter was started on 3/16/2023

2023-03-22 15:59 UTC, codinglikeagirl42 commented on content/relationships-or-mapping/reading/many-to-many/_index.md
> +date: 2022-12-15T09:16:07-06:00
These dates seem incorrect as the chapter was started on 3/16/2023

2023-03-22 15:59 UTC, codinglikeagirl42 commented on content/relationships-or-mapping/reading/many-to-many/_index.md
> +lastMod: 12/15/22 # UPDATE ANY TIME CHANGES ARE MADE
```suggestion
lastMod:  # UPDATE ANY TIME CHANGES ARE MADE
```

2023-03-22 16:49 UTC, codinglikeagirl42 commented on content/relationships-or-mapping/reading/one-to-many/_index.md
> +date: 2022-12-15T09:16:07-06:00
These dates seem incorrect as the chapter was started on 3/16/2023

2023-03-22 16:49 UTC, codinglikeagirl42 commented on content/relationships-or-mapping/reading/primer-on-lambda-expressions/_index.md
> +date: 2022-12-15T09:16:07-06:00
These dates seem incorrect as the chapter was started on 3/16/2023

2023-03-22 16:49 UTC, codinglikeagirl42 commented on content/relationships-or-mapping/reading/primer-on-lambda-expressions/_index.md
> +lastMod: 12/15/22 # UPDATE ANY TIME CHANGES ARE MADE
```suggestion
lastMod:  # UPDATE ANY TIME CHANGES ARE MADE
```

2023-03-22 16:52 UTC, codinglikeagirl42 commented on content/relationships-or-mapping/reading/some-setup/_index.md
> +date: 2022-12-15T09:16:07-06:00
```suggestion
date: 2023-03-16T09:16:07-06:00
```

2023-03-22 16:53 UTC, codinglikeagirl42 commented on content/relationships-or-mapping/_index.md
> +date: 2022-12-15T09:16:07-06:00
```suggestion
date: 2023-03-16T09:16:07-06:00
```

2023-03-22 17:05 UTC, codinglikeagirl42 commented on content/relationships-or-mapping/exercises/_index.md
> +date: 2022-12-15T09:16:07-06:00
```suggestion
date: 2023-03-16T09:16:07-06:00
```

2023-03-22 17:06 UTC, codinglikeagirl42 commented on content/relationships-or-mapping/next-steps.md
> +date: 2022-12-15T09:16:07-06:00
```suggestion
date: 2023-03-16T09:16:07-06:00
```

2023-03-22 17:06 UTC, codinglikeagirl42 commented on content/relationships-or-mapping/reading/_index.md
> +date: 2022-12-15T09:16:07-06:00
```suggestion
date: 2023-03-16T09:16:07-06:00
```

2023-03-22 17:06 UTC, codinglikeagirl42 commented on content/relationships-or-mapping/reading/many-to-many/_index.md
> +date: 2022-12-15T09:16:07-06:00
```suggestion
date: 2023-03-16T09:16:07-06:00
```

2023-03-22 17:07 UTC, codinglikeagirl42 commented on content/relationships-or-mapping/reading/one-to-many/_index.md
> +date: 2022-12-15T09:16:07-06:00
```suggestion
date: 2023-03-16T09:16:07-06:00
```

2023-03-22 17:09 UTC, codinglikeagirl42 commented on content/relationships-or-mapping/reading/some-setup/_index.md
> +lastMod: 12/15/22 # UPDATE ANY TIME CHANGES ARE MADE
```suggestion
lastMod:  # UPDATE ANY TIME CHANGES ARE MADE
```

2023-03-22 17:09 UTC, codinglikeagirl42 commented on content/relationships-or-mapping/reading/types-of-relationships/_index.md
> +lastMod: 12/15/22 # UPDATE ANY TIME CHANGES ARE MADE
```suggestion
lastMod:  # UPDATE ANY TIME CHANGES ARE MADE
```

2023-03-22 17:09 UTC, codinglikeagirl42 commented on content/relationships-or-mapping/reading/videos/_index.md
> +date: 2022-12-15T09:16:07-06:00
```suggestion
date: 2023-03-16T09:16:07-06:00
```

2023-03-22 17:10 UTC, codinglikeagirl42 commented on content/relationships-or-mapping/reading/videos/_index.md
> +lastMod: 12/15/22 # UPDATE ANY TIME CHANGES ARE MADE
```suggestion
lastMod:  # UPDATE ANY TIME CHANGES ARE MADE
```

2023-03-22 17:15 UTC, codinglikeagirl42 commented on content/relationships-or-mapping/reading/videos/_index.md
> +{{< youtube 9mBJLk5eNnA >}}
Sound on this video is too low, could barely hear with volume at maximum.  Also suggest moving this walkthrough to a separate page after creating a one-to-many relationship and before some-setup, the razor views chapter is a good example of video placement.

2023-03-22 17:23 UTC, codinglikeagirl42 commented on content/relationships-or-mapping/reading/one-to-many/_index.md
> +The `CategoryId` property functions as a [foreign key](https://education.launchcode.org/csharp-web-dev-curriculum/). EF will create a `CategoryId` column in the `Event` table. The value of this colum
Foreign Key link needs updating.

2023-03-22 17:32 UTC, codinglikeagirl42 commented on content/relationships-or-mapping/reading/some-setup/_index.md
> +The steps to add this code follow the exact same process that we used to add a [persistent EventCategory class](orm1-exercises), so we won't go through them in detail here.
Please update link for persistent EventCatagory.

2023-03-22 17:39 UTC, codinglikeagirl42 requested changes
Mostly minor changes to meta data and updating links.  Both videos have an issue with sound. Let me know if you have any questions. Please resubmit after changes for a second review.

2023-03-23 15:18 UTC, gildedgardenia commented on content/relationships-or-mapping/reading/videos/_index.md
> +{{< youtube W5cs3MWi7Ss >}}
John will re-upload this upon his return!

2023-03-23 15:27 UTC, gildedgardenia commented on content/relationships-or-mapping/reading/one-to-many/_index.md
> +The `CategoryId` property functions as a [foreign key](https://education.launchcode.org/csharp-web-dev-curriculum/). EF will create a `CategoryId` column in the `Event` table. The value of this colum
FIxed!

2023-03-23 15:29 UTC, gildedgardenia commented on content/relationships-or-mapping/next-steps.md
> +1. [Learn Entity Framework](https://learn.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key)
Fixed!

2023-03-23 19:24 UTC, codinglikeagirl42 approved these changes
Looks good, merge away!

2023-03-23 21:22 UTC, merged